source "https://rubygems.org"

# Specify your gem's dependencies in mcp-rails.gemspec
gemspec path: "../.."

gem "sqlite3"
gem "puma"
gem "mcp-rb", git: "https://github.com/Tonksthebear/mcp-rb", branch: "nested-arguments"
